version: '4'
services:
  postgres:
    image: postgres:latest
    container_name: nest-mikro-orm
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    ports:
      - 5433:5432
